### ISSUE TITLE
Scrape packagist for known extensions?

### ISSUE THREAD

**Issue by Danack** [gophp7/gophp7-ext#20]
Some extensions are not currently listed e.g. https://github.com/nrk/phpiredis

At least some of these missing extensions could be discovered by looking at the composer files for projects on packagist, and inspecting the suggest block e.g. https://github.com/nrk/predis/blob/v1.0/composer.json

```
"suggest": {
        "ext-phpiredis": "Allows faster serialization and deserialization of the Redis protocol",
        "ext-curl": "Allows access to Webdis when paired with phpiredis"
    },
```

**Comment by auroraeosrose** [comment]
Feel free to do this for any extensions that are missing
