### ISSUE TITLE
Zbarcode (barcode recognition) and libpuzzle (image recognition)

### ISSUE THREAD

**Issue by nitinsbuzz** [gophp7/gophp7-ext#33]

**Comment by jorissteyn** [comment]
For the record, I've made progress on php-zbarcode: https://github.com/mkoppanen/php-zbarcode/issues/22

**Comment by nitinsbuzz** [comment]
Great! Looking forward to it!

**Comment by jorissteyn** [comment]
Did php-libpuzzle too: https://github.com/alfa-jpn/php-libpuzzle5/pull/1

**Comment by lornajane** [comment]
Awesome work, thanks @jorissteyn  :)
